# Docker compose for local testing.
# Based upon https://renatogroffe.medium.com/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89
version: '3'

services:
  postgres-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "atestpasswordnonprod"
    ports:
      - "5432:5432"
    volumes:
      - ~/dev/transactions/postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-test:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mailinator.com"
      PGADMIN_DEFAULT_PASSWORD: "atestpasswordnonprod"
    ports:
      - "16543:16543"
    depends_on:
      - postgres-test
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
